"""init tables

Revision ID: 890ed750d467
Revises: 95d16e683d1a
Create Date: 2026-10-03 15:29:11.895496
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '890ed750d467'
down_revision: Union[str, None] = '95d16e683d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###