"""init tables

Revision ID: 8c5da5292ef6
Revises: 890ed750d467
Create Date: 2026-10-03 15:54:41.360823
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8c5da5292ef6'
down_revision: Union[str, None] = '890ed750d467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###