"""init tables

Revision ID: 95d16e683d1a
Revises: 
Create Date: 2026-10-03 15:08:13.895692
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '95d16e683d1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('placement', sa.String(length=128), nullable=False),
    sa.Column('dates', sa.String(length=256), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('photo_file_id', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sketches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('placement', sa.String(length=128), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=False),
    sa.Column('new_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('photo_file_id', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('placement', sa.String(length=128), nullable=False),
    sa.Column('duration', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('photo_file_id', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('sketches')
    op.drop_table('bookings')
    # ### end Alembic commands ###